### PR TITLE
Create Login.HTML

### PR DESCRIPTION
**Pull request by Mingkai1207**

### CODE REVIEW

**Comment by BernieHuang2008** [comment]
I think u can make changes based on the existing `login.html` and update this pr.

**Comment by Mingkai1207** [comment]
> Wait a minute, why I think I've seen this code before?

This is based on your code but adding a page when it is on loading

**Comment by Mingkai1207** [comment]
Also I make people can only wait when it’s on loading to ensure they won’t click other things

**Comment by BernieHuang2008** [comment]
> I think u can make changes based on the existing `login.html` and update this pr.

Ok, then you can do this to let me know what has changed, and make the git tree more beautiful.

I think simply 
1. rename your file in your local environment, 
2. squash your 3 commits (will be 4 of you do the first step) , using `git rebase -i HEAD~4`.
3. then use `git rebase main` to rebase your branch.
4. Force push it by `git push --force`

**Comment by Mingkai1207** [comment]
> > I think u can make changes based on the existing `login.html` and update this pr.
> 
> Ok, then you can do this to let me know what has changed, and make the git tree more beautiful.
> 
> I think simply
> 
> 1. rename your file in your local environment,
> 2. squash your 3 commits (will be 4 of you do the first step) , using `git rebase -i HEAD~4`.
> 3. then use `git rebase main` to rebase your branch.
> 4. Force push it by `git push --force`
> 
> Will be enough.

Ok, wait a minute

**Review by BernieHuang2008 — APPROVED** [review]

**Comment by BernieHuang2008** [comment]
i shall check its functions after merging

**Comment by BernieHuang2008** [comment]
@Mingkai1207 maybe you should learn what is `squash` though.

**Comment by Mingkai1207** [comment]
> @Mingkai1207 maybe you should learn what is `squash` though.

Hhhhhok

**Pull request merged**
